Update requirements.txt
itsdangerous==2.0.1 because of ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/dist-packages/itsdangerous/__init__.py)